apiVersion: appstudio.redhat.com/v1alpha1
kind: Component
metadata:
  name: release-component
  namespace: dev-release-team-tenant
  annotations:
    image.redhat.com/generate: 'true'
    skip-initial-checks: 'false'
spec:
  application: release-application
  componentName: release-component
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
  source:
    git:
      url: "https://github.com/scoheb/dc-metro-map"
  targetPort: 50051
