apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  name: release-releaseplanadmission
  namespace: managed-release-team-tenant
spec:
  application: release-application
  origin: dev-release-team-tenant
  releaseStrategy: release-strategy
